micronaut:
  server:
    port: 8888
    ssl:
      enabled: false

mockito:
  test:
    enabled

alma-api:
  apiKey: no-key-needed-for-testing

HMAC:
  secret: 123456

admin:
  username: unit-test
  password: test-unit