micronaut:
  server:
    host: 0.0.0.0
    port: 8080
    netty:
      responses:
        file:
          cache-seconds: 8640000
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/assets/**"
        paths: "classpath:views/assets"
  security:
    intercept-url-map:
      - pattern: /**
        access:
          - isAnonymous()
  http:
    client:
      read-timeout: 30s

alma-api:
  url: https://api-eu.hosted.exlibrisgroup.com/almaws/v1/
  mmsId: 994889360105506
  holdingId: 2236603930005506
  location: RESE
  page-size: 100

gadget-availability:
  image-ext: .jpg

HMAC:
  algorithm: HmacSHA256
  #secret: <provide via commandline on prod '-DHMAC.secret=123456'>
