micronaut:
  server:
    port: 8080
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/assets/**"
        paths: "classpath:views/assets"

alma-api:
  url: https://api-eu.hosted.exlibrisgroup.com/almaws/v1/
  mmsId: 994889360105506
  holdingId: 2236603930005506
  page-size: 100

gadget-availability:
  image-ext: .png  

HMAC:
  algorithm: HmacSHA256
  #secret: <provide via commandline on prod '-DHMAC.secret=123456'>